language: python

python:
    - "2.6"
    - "2.7"
    - "pypy"

#install deps
install:
    - "pip install -r requirements.txt -vvv"
    - "pip install . -vvv"
      #- "python setup.py install"
    - "cd phlaskr"
    - "./mk_local_settings.py"

# tests
script: 
    - "nosetests"
    - "py.test tests.py"
