"""removed unique

Revision ID: 13723c1443c8
Revises: 2baeb8a1c050
Create Date: 2015-06-18 02:39:59.044036

"""

# revision identifiers, used by Alembic.
revision = '13723c1443c8'
down_revision = '2baeb8a1c050'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
