"""added comments.date_added

Revision ID: 189db6cf953a
Revises: 39fae785297b
Create Date: 2015-06-19 14:56:28.108843

"""

# revision identifiers, used by Alembic.
revision = '189db6cf953a'
down_revision = '39fae785297b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.DateTime(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('date_added')

    ### end Alembic commands ###
