"""added public_users

Revision ID: 1917897a6c2f
Revises: 41055d7b513c
Create Date: 2015-06-21 23:53:21.159511

"""

# revision identifiers, used by Alembic.
revision = '1917897a6c2f'
down_revision = '41055d7b513c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_users',
    sa.Column('_pwhash', sa.Text(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'],name="pu_fk1"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username',name='unk_usr')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('public_users')
    ### end Alembic commands ###
