"""changed pw stuff

Revision ID: 2baeb8a1c050
Revises: 29ecb5c37c6
Create Date: 2015-06-17 23:56:05.829415

"""

# revision identifiers, used by Alembic.
revision = '2baeb8a1c050'
down_revision = '29ecb5c37c6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_users', sa.Column('_pwhash', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('app_users', '_pwhash')
    pass
    ### end Alembic commands ###
