"""changed comment stuff

Revision ID: 39fae785297b
Revises: 13723c1443c8
Create Date: 2015-06-18 15:41:45.929121

"""

# revision identifiers, used by Alembic.
revision = '39fae785297b'
down_revision = '13723c1443c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('subject', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key('comments', 'app_users', ['author_id'], ['id'])
        batch_op.create_foreign_key('comments', 'posts', ['post_id'], ['id'])
        batch_op.drop_column('parent_post_id')
        batch_op.drop_column('title')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(u'uq_pst_titid', type_='unique')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_unique_constraint(u'uq_pst_titid', ['title', 'id'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('parent_post_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('comments', 'posts', ['parent_post_id'], ['id'])
        batch_op.drop_column('subject')
        batch_op.drop_column('post_id')
        batch_op.drop_column('content')
        batch_op.drop_column('author_id')

    ### end Alembic commands ###
