"""added posts.author_id

Revision ID: 41055d7b513c
Revises: 189db6cf953a
Create Date: 2015-06-21 14:29:03.046863

"""

# revision identifiers, used by Alembic.
revision = '41055d7b513c'
down_revision = '189db6cf953a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('posts', 'app_users', ['author_id'], ['id'])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(type_='foreignkey')
        batch_op.drop_column('author_id')

    ### end Alembic commands ###
